#!/bin/bash

echo ${PWD}

echo -n "Enter project name: "
read project_name
# echo -n "Enter site domain: "
# read domain_name

project_code=`echo ${project_name} | tr '[:upper:]' '[:lower:]'`
project_code=echo "${project_code/" "/"_"}"

echo ${project_code}

git clone https://github.com/AKEB/template_project.git "${PWD}"

rm -rf "${PWD}/.git/"
rm -rf "${PWD}/create_project"
rm -rf "${PWD}/README.md"

sed -i -e "s/__PROJECT_NAME__/${project_code}/g" "${PWD}/docker/docker-compose.yml"


# wget --no-check-certificate -q -O "${PWD}/.gitignore" "https://raw.githubusercontent.com/AKEB/template_project/main/.gitignore"
# wget --no-check-certificate -q -O "${PWD}/.editorconfig" "https://raw.githubusercontent.com/AKEB/template_project/main/.editorconfig"


# echo <<EOF

# EOF > ${PWD}/.editorconfig
